version: '3.3'
services:
  meltano:
    build:
      # Build using the Dockerfile in the current directory
      context: .
    # Define image name, optionally with a tag e.g. meltano_bbm:v1
    image: meltano_bbm