version: '3.3'
services:
  meltano:
    build:
      # Build using the Dockerfile in the current directory
      context: .
    # Define image name, optionally with a tag e.g. meltano_bbm:v1, else it will default to latest
      args:
        # Passing the argument to the Dockerfile
        PROJECT_ROOT: ${PROJECT_ROOT}
    # env_file:
    #   - .env
    image: meltano_bbm